### ISSUE TITLE
Render 2D scenes as a texture fixed in virtual 3D space

### ISSUE THREAD

**Issue by morallo** [Prof-Butts/xwa_ddraw_d3d11#10]
Currently, the 2D scenes are "sticked to your face", which is disorienting and prevents you use your head movements to look to different places.

The usual model to represent 2D screens in VR is to create a virtual screen, fixed in the virtual world.

**Comment by Trevor89** [comment]
Agreed and I beleve this was already in the pipeline - or at least discussed?

**Comment by morallo** [comment]
I think this can be done with OpenVR overlays. I will give it a go after I finish with the performance/latency.

**Comment by Prof-Butts** [comment]
There's already a 3D vertex buffer that is used to render the 2D image. All
we need to do is enable the inverse of the camera transform matrix so that
it "stays in place" while looking around. This is probably easier than
using OpenVR overlays.

**Comment by morallo** [comment]
> There's already a 3D vertex buffer that is used to render the 2D image. All we need to do is enable the inverse of the camera transform matrix so that it "stays in place" while looking around. This is probably easier than using OpenVR overlays.

My (lack of) understanding of the view transformations and underlying math made it easier in my head to use overlays. No need to calculate anything, you just define the initial position in the tracked universe and the compositor does the rest.

But you surely know better! If you can give any pointers, I can try it out

**Comment by Prof-Butts** [comment]
See:

https://github.com/Prof-Butts/xwa_ddraw_d3d11/commit/10eae1aa7b86f342e0825f9b4696e69df753b16d

This exposed an artifact when the menu is pulled up while flying, so that still has to be fixed.

**Comment by morallo** [comment]
For me this works well enough, I think you should close this one @Prof-Butts

**Comment by Prof-Butts** [comment]
Alright, sounds good! Now I just need to figure out how to close the issue!
