### ISSUE TITLE
Use a consistent tracking pose between CockpitLook and ddraw VR rendering

### ISSUE THREAD

**Issue by morallo** [Prof-Butts/xwa_ddraw_d3d11#28]
I have come back to XWA after some busy times, and re-started the campaign.
In some of the missions, the performance drops heavily, regardless of graphics settings. During this phases, the VR tracking degrades too much, and the reprojection features of SteamVR and Oculus are not working as they do in other games.

### The problem
Currently, the rendering performed internally by the XWA engine uses the 3D pose obtained in the last call to WaitGetPoses() performed in the previous frame. ([SteamVR.cpp#L143](https://github.com/Prof-Butts/Hook_XWACockpitLook/blob/2e634e616a6a9d857eb57a405f50829913ac9a72/SteamVR.cpp#L143)). This is executed at the beginning of the frame, before any geometry calculation in the legacy engine.

However, the poses used by ddraw.dll to render the final image of that frame are obtained again directly from OpenVR during the Direct3DDevice::Execute(), through a new call to WaitGetPoses(). Since this happens after all the CPU work in the XWA engine has finished (just before the D3D11 rendering), this pose is different than the one used by the hook.

When the performance is good (frame time is low), the difference between those poses is negligible (<10ms). However, when the performance drops in the XWA engine (due to its intrinsic limitation of not using the GPU), the time between the execution of the hook, and the Execute() increases to multiple VSYNCs. In VR, this level of latency for the tracking is very noticeable.
Also, it probably messes up the tracking prediction algorithms.

I believe this is one of the, if not the main reason behind the jitter/shaking visible on game world objects when moving the head during low framerate periods.

One evidence supporting my hypothesis is that the HUD is totally stable and smooth (thanks to ASW-reprojection), even during framerate drops. I believe the HUD is rendered completely by ddraw.dll so the outdated pose used in the hook does not affect it. .

### The solution

The pose needs to be calculated at the very beginning of the frame, just before the geometry calculations are started. In the current engine, that means at the CockpitLook hook before the CPU rendering starts.

Then, at the time of VR re-rendering, instead of obtaining again a new pose, the pose obtained by CockpitLook hook should be used.

### The pending question

What is the best way to pass that information from the hook to the ddraw.dll?
Since they are 2 different modules, I believe it's not possible to use a simple global variable.

Probably the best alternative would be to create a function in the hook dll and call it from the ddraw.dll, after referencing it as external library.

@Prof-Butts what do you think?

**Comment by morallo** [comment]
I was actually looking at an old branch (maybe it would be good to merge the latest commits to master?)

After my last PR, in fact the Hook uses GetLastPoses().
But it should be using instead the updated poses from GetDeviceToAbsoluteTrackingPose(), and then maybe ddraw.dll can just call GetLastPoses() to obtain the same.

**Comment by Prof-Butts** [comment]
Right, the master branch is a bit behind -- sorry about that. Both the CockpitLook dll and ddraw share the same heap, so it's easy to have them talk to each other with, say, a memory-mapped file. Plus we wouldn't need a mutex either since XWA evaluates the Cockpitlook before the 3D path.

I think we can try the approach you're suggesting, but we need to be careful. The rendering thread must call the right APIs or nothing will show up. But, by all means give it a try! If it doesn't work, we'll just use a memory-mapped file to share the pose between these dll's.

**Comment by morallo** [comment]
I have tested this by moving the call to WaitGetPoses() to Hook_CockpitLook.dll->SteamVR.cpp, and using GetLastPoses() in ddraw.dll instead.
The performance is definitely worse, in terms of FPS, but the tracking feels a lot more consistent. The game world objects don't jump around so much. They're just low FPS to update.

To implement it without a performance impact, I need to use GetDeviceToAbsoluteTrackingPose() in CockpitLook and leave the sync call to WaitGetPoses() in ddraw.dll.

But as I thought, I need to implement a way to pass the pose info from Hook_CockpitLook.dll to ddraw.dll, because I can't rely on GetLastPoses() (it doesn't take the GetDeviceToAbsoluteTrackingPose() into account, it will give the poses from the previous frame).

I will try to do it by storing the pose in a global variable and a method to access it in Hook_CockpitLook.dll and calling it from ddraw.dll.

**Comment by morallo** [comment]
I managed to implement a first version:
https://github.com/morallo/xwa_ddraw_d3d11/commit/fc21161a97a5031a628ddb8e0e243b1118e87bc2
https://github.com/morallo/Hook_XWACockpitLook/commit/f405faebb17b0b8b6bd505487e0c942d260d0799

I started from the UDP branch to modify Hook_CockpitLook. @Prof-Butts can you confirm that's the latest I should be using?

The disappointing news is that the performance is again quite bad, and the tracking is **consistently** stuttery now, which means it impacts all elements on screen (including the HUD). I need to do more tests and analyze some XPerf captures with GPUView to find out the root cause.

**Comment by Prof-Butts** [comment]
Yeah, the latest version of the CockpitLook hook is in the UDP branch. Sorry, I really need to clean up my branches.

**Comment by morallo** [comment]
It turns out the fault was not in my code, but because I was using Virtual Desktop (wireless VR streaming) to play in Oculus Quest 2. When I changed back to Oculus Link (the official USB mode to use Quest2 on PC), I got the performance back.

I fixed an issue with the tracking in 2D mode and I think it's ready for beta-testing. I tried again with your latest beta from October and I can clearly notice an improvement. The tracking is much smoother with my latest code.

I will upload the compiled DLLs and post in the beta thread of the forum to ask for testers.

To ease the linking between ddraw and cockpitlook DLLs, I added the hook as a reference in ddraw solution.
Since both codes need to be in sync for everything to work properly, @Prof-Butts do you think we could include the hook in the ddraw repository as a submodule, and set it up so that everything is built together?

**Comment by Prof-Butts** [comment]
Hey @morallo!

Let me fix my mess and get the master branch up to date. I've just got a minor concern with your proposed fix. There are many people that don't like the effects in ddraw that much, but would like to use TrackIR. For those guys I usually tell them to remove my ddraw and just keep the CockpitLook hook. In your fix above, it looks like ddraw will now be needing a function from the CockpitLook hook through a static link. I think the approach is fine, but we need to use run-time linking instead. That way, the function in CockpitLook only gets loaded if people are running the SteamVR path.

Also, another minor point: can you drop the log_debug in the error path (when the pose isn't valid)? Logging induces a very noticeable penalty in performance. We can put that line inside a #define DEBUG or something like that.

**Comment by Prof-Butts** [comment]
@morallo: I keep thinking about this and I'm not sure run-time linking is a great idea either as it would introduce another dependency. Both DLLs see the same heap, so it's just a matter of sending a 32-bit pointer between them and that's it. However, let's go ahead and test this for now -- just bear in mind that we'll probably come back later to polish it a little bit :)

**Comment by morallo** [comment]
Thanks for the feedback!
I have removed the log_debug(). It was there before these latest changes. I thought there was no impact unless you had a listener actually capturing the messages, but it's not really necessary in such a performance critical function.

About linking I agree that dynamic linking would be a better option, but the function exported does not need to be used by the dll if it's not needed. So there is no dependency unless you are using SteamVR. I have tested, and the SteamVR tracking still works when using Jeremy's dll.

In terms of performance, would the shared heap be more efficient?

**Comment by Prof-Butts** [comment]
For dynamic linking you don't need to include the hook's headers in ddraw, you just need the function declaration itself. Since it's only one function, it probably makes sense to just copy the declaration. You're right that there shouldn't be any static link dependencies and the DLL reference is only loaded for SteamVR.

Using the shared heap would be faster than calling a function from another DLL because it's just a regular read from memory. I'm looking for options on how to do this, and this looks like a nice approach:

https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2008/h90dkhs0(v=vs.90)?redirectedfrom=MSDN

Perhaps we can use a named data segment to store the SteamVR pose.

**Comment by Prof-Butts** [comment]
@morallo: both the CockpitLook hook and ddraw master branches have been refreshed and tagged appropriately. Can you update your PRs? Also, can you explain again how you'd like to keep working in the future? I'm used to having the master branch as the stable release at all times and do experiments on other branches. My mistake is that I seldom refresh the master branch. I'll keep making experiments on the Release_1_1_5 branch for now.

**Comment by morallo** [comment]
PRs updated. We can discuss about branching strategy in #15

**Comment by morallo** [comment]
Giving another thought and [some reading](https://docs.microsoft.com/en-us/cpp/build/linking-an-executable-to-a-dll?view=msvc-160) about the linking... I think I understand now better your first comments. There are 2 scenarios:

- User wants CockpitLook tracking without effects (original Jeremy's dll)
    - This works with either static or dynamic linking, since Jeremy's dll will never import or call the exported function in the hook.
- User wants effects without tracking
    - Static linking: ddraw.dll will need the hook even if will never be used. This can complicate merges back into Jeremy's, if that ever happens.
    - Dynamic Linking: will only try to load the DLL if the user wants to use tracking.

So, dynamic linking is the best option and should be easier to implement, until we implement any other shared memory option.

**Comment by Prof-Butts** [comment]
Well, it turns out that sharing stuff between these two DLLs may be rather easy. I just wrote the address of a char[32] to disk, from the CockpitLook hook, then I read that same address in ddraw and assigned it to a char* and it worked. Also, Jeremy just told me that there are some offsets in the PlayerData table that are unused so we can use that to share pointers as well. In other words: we may not even need dynamic linking at all.

**Comment by Prof-Butts** [comment]
@morallo: I just updated the CockpitLook hook to use the LocalProperties (I removed a couple of hard-coded paths as well). Let me implement the shared memory option as I think that would avoid any dependencies between these DLLs and it's faster anyway.

**Comment by morallo** [comment]
I have re-implemented it with the memory sharing functions, but it´s still not ready.
I created a new branch and a draft PR #35 (WIP).

**Comment by morallo** [comment]
@Prof-Butts as you merged #35 I think this issue can be closed, unless you think that there is something pending.
