### ISSUE TITLE
Code doesn't build with OpenVR >= 1.13.10

### ISSUE THREAD

**Issue by morallo** [Prof-Butts/xwa_ddraw_d3d11#32]
The `ResetSeatedZeroPose()` method was moved from `IVRSystem` to `IVRChaperone`:
https://github.com/ValveSoftware/openvr/commit/6192a30d2dee3d43731da0831e8639fbf9b90943

In the latest versions, it does not even exist. The equivalent would be calling `ResetZeroPose(vr::TrackingUniverseSeated)`.

There are probably other incompatibilities.

@Prof-Butts what version of openvr are you using? It should probably be specified in the requirements.

**Comment by Prof-Butts** [comment]
Ugh, so we also have to play catch with these guys? Oh well. This is the version I'm using (looks like it's from Jan 2020):

https://www.dropbox.com/s/4tv2vz9n6q20a5g/openvr-master.zip?dl=0

However, I suggest we use the latest OpenVR and create a new branch to do the necessary fixes.

**Comment by morallo** [comment]
Closed by #43
