### ISSUE TITLE
Jitter from cockpit look

### ISSUE THREAD

**Issue by morallo** [Prof-Butts/xwa_ddraw_d3d11#40]
When in VR, while moving the view with the headset there is some shake of the models specially visible in the cockpit and also in the ship markers (brackets).

There is also some jitter in non-VR mode, when cockpit inertia is enabled. When moving around and the inertia kicks in, there is some noticeable jitter. However, it is much less disturbing in 2D mode, with a lower FOV.

There is no jitter if all types of headtracking and inertia are disabled.

This makes me think that the jitter is related to the hack used to override the camera position/direction in [Hook_XWACockpitLook](https://github.com/Prof-Butts/Hook_XWACockpitLook)

**Comment by Prof-Butts** [comment]
Yes, I also think this jitter is happening because the cockpit shake was hijacked to implement positional tracking. I'm taking a deep look at this problem now.

**Comment by morallo** [comment]
I am working on improving the jitter and the performance in https://github.com/morallo/xwa_ddraw_d3d11/tree/pose_prediction_jitter_fix

Some of the experimental changes have been merged into master. Still not included in any betas but if you compile from the current master, you can enable it by setting a variable in `CockpitLook.cfg:`

`pose_corrected_headtracking = 1`

**Comment by morallo** [comment]
Fixed in #51
