### ISSUE TITLE
No image in HMD in the hangar

### ISSUE THREAD

**Issue by morallo** [Prof-Butts/xwa_ddraw_d3d11#42]
The latest beta fix for the latency and jitter (https://github.com/Prof-Butts/xwa_ddraw_d3d11/pull/41) removes the `&& !g_playerInHangar` condition from `GetSteamVRPositionalData()`, which was never `True`, so the tracking was always re-obtained in `ddraw.dll`, even while flying with CockpitLook active.

This fixes some of the jitter, but breaks the tracking in the hangar, because `g_b3dRendering=true` so ddraw.dll tries to get the poses from CockpitLook when it is not active. WaitGetPoses() is never executed so nothing is rendered to the HMD.

We need to find the real value where the game stores the hangar state and re-add the condition.

**Comment by morallo** [comment]
Fixed by 07157e4f79b695397a1c0b7f082b2c8a2cdadfd6 (added to #41)

**Comment by morallo** [comment]
This was solved by #41. You can close it @Prof-Butts.

**Comment by Prof-Butts** [comment]
Your fix has been merged into the master branch. Thanks!
