### ISSUE TITLE
White borders on 3D edges

### ISSUE THREAD

**Issue by morallo** [Prof-Butts/xwa_ddraw_d3d11#62]
https://forums.xwaupgrade.com/viewtopic.php?p=185827#p185827

![image](https://user-images.githubusercontent.com/2017580/160502077-fa781c15-193c-4fe8-8877-b15664904dfb.png)

**Comment by Prof-Butts** [comment]
Reportedly caused when MSAA and SSDO are enabled.

**Comment by morallo** [comment]
Fixed in https://github.com/Prof-Butts/xwa_ddraw_d3d11/commit/9adbf8ade2bfb0892efe89d969bbed31709ac422
